<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Outgoing Status_Active</name>
   <tag></tag>
   <elementGuidId>a097c59a-f974-43da-9b80-c9000a019e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Active']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae0f3171-6f26-4c2a-afbc-7dd551fd7716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>22494a55-b6b4-42a1-a079-7b1013c655cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>9d805325-8c83-49d5-9c63-fbd603a4b7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>70d551f1-1d7f-4a67-8320-22dd6334ae2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>146f946b-da64-4827-80ff-8099a10a5040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusOutgoing</value>
      <webElementGuid>40db7456-151a-4b9c-aab2-2d88029665c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13426560-d455-49f7-ba68-bbec50f2e525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;flex flex-row gap-3 col-3&quot;]/div[@class=&quot;flex flex-wrap ng-star-inserted&quot;]/p-radio-button[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;p-radiobutton p-component p-radiobutton-checked&quot;]/input[@id=&quot;Active&quot;]</value>
      <webElementGuid>6d7e7115-c025-4dd9-b4e6-0cd64307e679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Active']</value>
      <webElementGuid>58828e1c-d974-459c-82f7-6a3a3ae30668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div[5]/div[2]/p-radio-button/div/input</value>
      <webElementGuid>4faf8914-276b-43d5-a1e5-0278c38db6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-radio-button/div/input</value>
      <webElementGuid>dce9a71c-167d-469f-acb1-e84e9c2ce126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Active' and @name = 'statusOutgoing']</value>
      <webElementGuid>cbfb487a-e659-40f1-84f7-50e52ddf3cb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
