<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Incoming Status_Inactive</name>
   <tag></tag>
   <elementGuidId>f75e89ef-c8d9-466c-a915-6364b3da8eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-radiobutton.p-component.p-radiobutton-checked > #Inactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Inactive'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e19ba11-2608-45ed-9d63-f0df6fc9ae5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5cc0277d-eb49-4aca-95eb-ac056ace9fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>bdd98b6b-57e5-436e-bd55-ef9455e4f6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>9fa3c346-a3f1-4e27-b851-7768be8e6bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>34198945-39dc-4474-8281-8e409b9b42c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusIncoming</value>
      <webElementGuid>76cd0752-8bf1-4329-b8cd-d1225ecc29fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>853ee7b5-fe1a-47eb-aba8-548e708c087c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;flex flex-row gap-3 col-3&quot;]/div[@class=&quot;flex flex-wrap ng-star-inserted&quot;]/p-radio-button[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-radiobutton p-component p-radiobutton-checked&quot;]/input[@id=&quot;Inactive&quot;]</value>
      <webElementGuid>8323dd9e-2771-43c4-9ad6-c672199ef6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Inactive'])[2]</value>
      <webElementGuid>91dc5cc0-587e-479a-a2b6-e0da2311d859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div[7]/div/p-radio-button/div/input</value>
      <webElementGuid>3406a2c3-9ea2-4e28-927f-8fd01ca003e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/p-radio-button/div/input</value>
      <webElementGuid>65842d45-454a-4a5d-a670-173517ce4917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Inactive' and @name = 'statusIncoming']</value>
      <webElementGuid>4380413f-5f5e-401c-a0d6-6aa5e4c1736e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
