<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_userid</name>
   <tag></tag>
   <elementGuidId>06d0a700-d61e-48ad-92ea-9d1115eca4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53637648-54d3-4bdd-9ce3-a67485939575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userid</value>
      <webElementGuid>5cc11fa1-9c8d-4a0a-a860-ec030c0c77f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd1c256f-87ae-4c4a-896d-e3a07bdf34db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e80fe3c7-9acc-42cc-8878-eafca7a81091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userid</value>
      <webElementGuid>8bdf71e5-4cfb-490e-8eca-c0be5f8484b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Username</value>
      <webElementGuid>a77946bd-07e3-4169-92c1-c8a1356ed712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputtext-lg w-full ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d820d846-e092-41bc-9774-06bb1ea4cea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userid&quot;)</value>
      <webElementGuid>f82c7c94-42b3-432b-a525-418a5d40c8ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userid']</value>
      <webElementGuid>c2edeffd-9797-4354-a853-64741f44051d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9eca187b-a9a3-4807-8ff3-67967f652d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userid' and @type = 'text' and @placeholder = 'Masukan Username']</value>
      <webElementGuid>e4c30a9b-2af7-4663-b6ef-c4349af22e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
