<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_p-inputtext p-component ng-t_b30a64</name>
   <tag></tag>
   <elementGuidId>410fff5c-0f47-47c8-9a26-72bc0a8595cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2303701948-3.w-full.p-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6da4bb4-84e7-455a-9b4d-dbbed7928ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input</value>
      <webElementGuid>3cb15a56-0940-4cea-8033-30e5747259d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>54581554-d5ab-429e-b574-431ce7974b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Password</value>
      <webElementGuid>66379c34-164b-4187-b0ec-9f9dcede7679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e0c6aef-23c3-49e3-bbb7-7e301be81b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>554551b1-4ec9-4022-a4c1-c2eff76280e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secret&quot;)/div[@class=&quot;ng-tns-c2303701948-3 p-password-lg w-full p-password p-component p-inputwrapper p-variant-filled&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input&quot;]</value>
      <webElementGuid>945edaff-e102-4714-a7c6-91d585b83456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>72533908-1ef1-4e9d-850f-5d9366628fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-password[@id='secret']/div/input</value>
      <webElementGuid>6021f066-d86b-426f-8654-b15fdda7c504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-password/div/input</value>
      <webElementGuid>086fc438-65c3-4614-ab73-9485a7b0450b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Masukan Password']</value>
      <webElementGuid>65cb6fdc-038a-40b6-ba90-be0c9cc99b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
