<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_p-inputtext p-component ng-t_b30a64</name>
   <tag></tag>
   <elementGuidId>20cd20c6-a485-4ed2-89e8-52072b8bc96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2303701948-3.w-full.p-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c8cca41-4d44-47c6-acd9-3901b974dc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input</value>
      <webElementGuid>86243c37-b7b0-435f-bf00-8d89ad039e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5e22455d-8b69-461c-b3d6-e6628cfccffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Password</value>
      <webElementGuid>e82ee5cc-f420-4f6c-b4a5-50fdf07be867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f2e4799c-0223-454a-a327-fc0a521e3c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e9011fb-1f33-4826-861b-42cf355e9b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secret&quot;)/div[@class=&quot;ng-tns-c2303701948-3 p-password-lg w-full p-password p-component p-inputwrapper p-variant-filled&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input&quot;]</value>
      <webElementGuid>91cc135b-3cfa-4225-a2d6-12fb8b1ee049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>0338d7bf-21ac-45d3-a813-2cfa4edc3bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-password[@id='secret']/div/input</value>
      <webElementGuid>4bb423b0-10c9-4e2c-8b22-0fb99d98fe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-password/div/input</value>
      <webElementGuid>e4f1fa5e-28ea-4a16-9e9c-0f99dde55f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Masukan Password']</value>
      <webElementGuid>88d2acc0-9c50-4a8e-8407-f5f07b65902d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
