<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Proxy</name>
   <tag></tag>
   <elementGuidId>88e340ef-4eb4-472b-bd94-93bca9b4b2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pn_id_8_4_5_0']/div/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>747d6b1d-50e4-46ab-b8b8-7297851580a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 text-[#667085] transition-all duration-300</value>
      <webElementGuid>90de1fe9-32ec-45a9-b191-355751bced65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proxy</value>
      <webElementGuid>5b480959-16ab-4124-a2ed-8936e3a55feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_8_4_5_0&quot;)/div[@class=&quot;p-panelmenu-item-content ng-tns-c2533221881-15&quot;]/a[@class=&quot;flex align-items-center cursor-pointer text-[#667085] px-3 py-2 transition-all duration-300&quot;]/span[@class=&quot;ml-2 text-[#667085] transition-all duration-300&quot;]</value>
      <webElementGuid>9fe2c20c-cbef-4449-8ce3-0513879a8bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pn_id_8_4_5_0']/div/a/span[2]</value>
      <webElementGuid>b2a6fe15-61e7-43b1-a9e5-e437d02a02ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::span[2]</value>
      <webElementGuid>53f47d18-132b-48de-a392-4949df6c6070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction'])[2]/following::span[5]</value>
      <webElementGuid>d9220d3a-37cb-4d71-bc2c-d0e98be841ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Network Management Message'])[2]/preceding::span[2]</value>
      <webElementGuid>0588e4b5-0753-46f9-880d-4fd48be89771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recon File'])[1]/preceding::span[4]</value>
      <webElementGuid>c45a82f6-6a7b-41a1-b088-d0a2cab7ff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proxy']/parent::*</value>
      <webElementGuid>35b3b897-ace1-4c92-b63c-fac2a555c44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-panelmenu-sub/ul/li/div/a/span[2]</value>
      <webElementGuid>c5ba44b8-41ff-4953-b603-addcc5a02418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Proxy' or . = 'Proxy')]</value>
      <webElementGuid>fe1f08d5-b50c-467e-94d5-e06c5f7e10b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
