<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_userid</name>
   <tag></tag>
   <elementGuidId>212cb923-b626-4a76-a6ba-24597bf17808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84cf8493-b5b3-4523-af69-89c13b0a47ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userid</value>
      <webElementGuid>3d70cbc6-db7f-4edd-936d-8f6d10df13dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08e4e810-023d-4047-af92-43ef5a0948b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c199614c-0828-4167-99ea-584c688443e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userid</value>
      <webElementGuid>ef7b2b25-43a0-4d65-8f51-cfd394cf2afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Username</value>
      <webElementGuid>b722d54f-443d-4508-8eaa-b1055913cb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputtext-lg w-full ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>899267cf-b6cc-4935-b21a-f30e1b2d565b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userid&quot;)</value>
      <webElementGuid>0de9cf83-0b11-4445-a0f8-9b1def7be525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userid']</value>
      <webElementGuid>b2d2b76b-8411-40b4-97ea-334916eccefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>87857faf-9ab6-4d32-989d-97810f012835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userid' and @type = 'text' and @placeholder = 'Masukan Username']</value>
      <webElementGuid>dc53758f-2f25-4303-8d37-7f067672c720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
