<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_p-inputtext p-component ng-t_301fc3</name>
   <tag></tag>
   <elementGuidId>fa73c310-8e51-4527-ab9a-02ea95977259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2303701948-3.w-full.p-password-input.p-filled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30cf3190-48c3-4ead-a4b5-383b030a0806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input p-filled</value>
      <webElementGuid>d9bee88e-525e-4ff2-8458-5cfae19cfbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e41a8aac-8c6b-4de9-8528-71221bd40477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Password</value>
      <webElementGuid>88603f7c-26b0-4597-bf84-e840e3f088b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>59034dea-a68d-4dff-8314-4fcecc518dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b54e23b4-e89b-4bc5-9c6c-1ee879a1ebbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secret&quot;)/div[@class=&quot;ng-tns-c2303701948-3 p-password-lg w-full p-password p-component p-inputwrapper p-variant-filled p-inputwrapper-focus p-inputwrapper-filled&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input p-filled&quot;]</value>
      <webElementGuid>6341abe2-be3a-4a9b-a8bc-380c1cfb3ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>9b3a226b-c0f2-4410-bc9d-b7c0764c74e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-password[@id='secret']/div/input</value>
      <webElementGuid>47efb4de-1609-4887-8885-76e7a9ae845b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-password/div/input</value>
      <webElementGuid>489baab7-8c90-4b13-bdcf-f9fa9b89e7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Masukan Password']</value>
      <webElementGuid>b848f705-73fd-4c29-8e21-06e041a5ed13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
