<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input startdate</name>
   <tag></tag>
   <elementGuidId>3dcb5ecd-69d1-46f8-a20b-d41b7b120f69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2490469397-19.p-datepicker-input.p-filled.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77021ff5-c47a-4e73-b30a-670246be7f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14549333-21af-4671-a2be-b72595bdda94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>6ca07735-2594-4948-8fd1-59bf9183155f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>be3cc4ed-0ebf-48b1-a0f7-53b073722bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8f8935fc-7f97-44bf-af06-8d15962811cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8958184d-9fb1-42ca-b970-2b4074e23113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2490469397-19 p-datepicker-input p-filled ng-star-inserted</value>
      <webElementGuid>8b432eb8-6d19-4c5d-8cfd-6a381f9302bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41a36d70-a643-4917-aa72-e7d3b015ef23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_126_panel</value>
      <webElementGuid>aa574c67-7c27-4cb9-8e16-762a80165c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;field col-3&quot;]/p-calendar[@class=&quot;w-12 ng-tns-c2490469397-19 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c2490469397-19 p-datepicker p-component p-inputwrapper p-inputwrapper-filled p-inputwrapper-focus p-focus&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2490469397-19 p-datepicker-input p-filled ng-star-inserted&quot;]</value>
      <webElementGuid>b5ae2b66-b436-4594-94e3-149b647195b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>6779eb9c-540b-48ae-9aa3-4645928727bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[2]/p-calendar/span/input</value>
      <webElementGuid>028bfd32-0c11-4be3-8cb1-5c1fe8c968bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c7e73bf9-6039-43d4-ac08-dd7df437713e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>cd92263f-02f5-4639-bb63-63a8d3d7d5e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
