<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih CSV</name>
   <tag></tag>
   <elementGuidId>5c4c485d-c581-48ad-ac31-b45030f3acc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pn_id_165_0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pn_id_165_0 > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d311ead-ba92-4712-b0a3-66fce8523d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>ec99c658-c1ce-4e09-ae9a-aafe857c3530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV</value>
      <webElementGuid>06413fa3-b544-4e6d-bf1c-821353e89376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_165_0&quot;)/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>5246e5d8-fa3e-4325-8e2f-21f7313c52c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pn_id_165_0']/span</value>
      <webElementGuid>a11dd1e8-2ac8-4e52-9c63-7b5129baa591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[1]</value>
      <webElementGuid>50b6ff5b-3a1e-432e-9176-362d57ac4d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV-SEMICOLON'])[1]/preceding::span[1]</value>
      <webElementGuid>fb197b59-97ae-4ac8-a3a7-920e9fde97c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No selected item'])[1]/preceding::span[2]</value>
      <webElementGuid>9c2a2ca2-18b3-4f7e-b94e-8d4bec7bca2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>10f2fbf9-8c4b-41cd-abe9-f4bc309bd5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CSV' or . = 'CSV')]</value>
      <webElementGuid>1e63328e-464a-4020-ad83-677e71b204dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
