<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_KOMI Ref</name>
   <tag></tag>
   <elementGuidId>7d777791-c424-4163-b286-5f10e26dd8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#traceID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='traceID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#traceID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8ef03c8-5154-4fbb-b9cd-5b8d0da86c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>traceID</value>
      <webElementGuid>9f4bf3c5-a57d-417a-b4d3-5e042b0ba6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>traceID</value>
      <webElementGuid>0db0f016-d4be-489b-9d38-2c94619ef4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-pristine ng-valid ng-touched</value>
      <webElementGuid>7f54af89-7d5d-42e0-8cab-f6086c770ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;traceID&quot;)</value>
      <webElementGuid>ff6b859c-e593-495b-bc57-6e65aec4b412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='traceID']</value>
      <webElementGuid>6c2c59bf-4691-48d3-ba15-37f35bc63ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[8]/input</value>
      <webElementGuid>a423ed55-e554-4647-89a2-cb031e47ca93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>9dd90a64-339b-4060-83ec-d03912e95e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'traceID']</value>
      <webElementGuid>d780b143-5030-436a-8e86-47a86c79e7a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
