<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_KOMI Ref</name>
   <tag></tag>
   <elementGuidId>dc3b9a75-5de7-4134-8da6-f1417ab4c698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#komiUniqueId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='komiUniqueId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#komiUniqueId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0107a52b-c657-4606-bc45-42c2e8974a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>komiUniqueId</value>
      <webElementGuid>9df38b0a-8d1d-455c-9504-6e90d87e24d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>komiUniqueId</value>
      <webElementGuid>c1839451-6be4-4428-b353-169beda53778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0ec74eb0-e938-468d-86de-e7134a6c8462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;komiUniqueId&quot;)</value>
      <webElementGuid>654f6453-0185-44ba-a72d-38917f18a6df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='komiUniqueId']</value>
      <webElementGuid>57377d57-9951-48db-9415-20554bd22dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-accordion-content[@id='pn_id_201_accordioncontent_activePanelValue']/div/div/div[14]/input</value>
      <webElementGuid>c6d3f5ac-b399-4def-a91e-eafa4cd8ff7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>c557baf3-043a-4d03-8494-33461d204cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'komiUniqueId']</value>
      <webElementGuid>7d146355-d354-4823-a2f6-e1fc8830aaa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
