<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Show Advance Filter</name>
   <tag></tag>
   <elementGuidId>3f0c2096-911d-4983-be80-ffd4c2b5656b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_201_accordionheader_activePanelValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-accordion-header[@id='pn_id_201_accordionheader_activePanelValue']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pn_id_201_accordionheader_activePanelValue' and (text() = 'Show Advance Filter' or . = 'Show Advance Filter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show Advance Filter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-accordion-header</value>
      <webElementGuid>d0de08da-c5ce-4968-b36b-bb852a9ad74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-accordionheader</value>
      <webElementGuid>e53dec2b-8991-4da5-9eac-6cb503b438d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_201_accordionheader_activePanelValue</value>
      <webElementGuid>813ceef1-06c1-4e97-8617-36558649f355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cda67e28-86f9-467d-937e-8a4cea540e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_201_accordioncontent_activePanelValue</value>
      <webElementGuid>9c27bb52-5287-42fb-8673-f3feaefad9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7dc9b30f-c83f-41be-9275-0caa61f9f4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af36459d-f765-4732-9ee4-143a31069fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd66e4fc-228d-4e30-81f9-c3e55d40df01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>420d470a-20ca-4597-b789-a595f769c105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14b33a24-7094-4b6a-9e87-4009a01f586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>accordionheader</value>
      <webElementGuid>08a22ea0-d5cc-4272-9668-e3dfdd7e7eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show Advance Filter</value>
      <webElementGuid>60873fec-fe04-4598-86bd-e852db19a8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_201_accordionheader_activePanelValue&quot;)</value>
      <webElementGuid>4ea01b6a-6df7-49e0-a8fb-714be5e28505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-accordion-header[@id='pn_id_201_accordionheader_activePanelValue']</value>
      <webElementGuid>0df8f2b9-7f13-44c1-93e3-3e78af3e80a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[19]/p-accordion/p-accordion-panel/p-accordion-header</value>
      <webElementGuid>2f1bb205-335d-4276-94b0-86375c6bd71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOMI Ref'])[1]/following::p-accordion-header[1]</value>
      <webElementGuid>c9a78b0e-68ff-4e47-8aee-1b78070afb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BI-Fast ID'])[1]/following::p-accordion-header[1]</value>
      <webElementGuid>fe09e20c-5f31-4322-803c-2cbcc52720eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Data'])[2]/preceding::p-accordion-header[1]</value>
      <webElementGuid>0add185b-1543-4404-8788-5a4e4249aded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Transfer'])[4]/preceding::p-accordion-header[1]</value>
      <webElementGuid>d5b8e8d0-bbd9-4d57-a50e-335c41538c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show Advance Filter']/parent::*</value>
      <webElementGuid>8d1432da-3b58-4e32-be70-46dc7adb2a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-accordion-header</value>
      <webElementGuid>864e1e86-8d6d-4c1b-8380-8df54bea1356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-accordion-header[@id = 'pn_id_201_accordionheader_activePanelValue' and (text() = 'Show Advance Filter' or . = 'Show Advance Filter')]</value>
      <webElementGuid>f007ccc9-f096-4db1-961b-60c84623d6e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
