<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Show Advance Filter</name>
   <tag></tag>
   <elementGuidId>3f0c2096-911d-4983-be80-ffd4c2b5656b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_201_accordionheader_activePanelValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-accordion-header[@id='pn_id_201_accordionheader_activePanelValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show Advance Filter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-accordion-header</value>
      <webElementGuid>d649efe4-fdf9-45b1-a8fb-b1b92144b007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-accordionheader</value>
      <webElementGuid>dfad8d01-aeae-401f-901d-1f8baf2e6a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_201_accordionheader_activePanelValue</value>
      <webElementGuid>f0dab82d-270c-4e46-b122-c3abf4d194b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e05a4075-8fed-4504-92a0-de716e274812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_201_accordioncontent_activePanelValue</value>
      <webElementGuid>0b85d99d-e387-44bc-af1e-a33c0391fe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db43b0ba-0a6e-4f03-99fd-913f994d96fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93de4f54-5fe8-45d5-8d8d-24797767b90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>260599ab-0911-4856-96c6-118c0488ec5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e15ff1e5-ec4c-4884-9663-57d267eaf1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f53752c-6a34-461a-b242-d166023d6944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>accordionheader</value>
      <webElementGuid>46446825-b373-4549-96e1-4e3ce9245826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show Advance Filter</value>
      <webElementGuid>7f2d611a-52e9-4f07-a159-e7d25a7c5726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_201_accordionheader_activePanelValue&quot;)</value>
      <webElementGuid>81478d17-7381-47c3-9d18-dfa5202ca393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-accordion-header[@id='pn_id_201_accordionheader_activePanelValue']</value>
      <webElementGuid>3e566b41-ff95-421e-a368-664e55185fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[19]/p-accordion/p-accordion-panel/p-accordion-header</value>
      <webElementGuid>043a99d8-2f50-4d2e-8260-a08e0daf4ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOMI Ref'])[1]/following::p-accordion-header[1]</value>
      <webElementGuid>49dcd4c1-735c-40b8-a3c4-4208cdc670ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BI-Fast ID'])[1]/following::p-accordion-header[1]</value>
      <webElementGuid>b7d0acff-da37-449c-9b2e-80b12aeb6ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Data'])[2]/preceding::p-accordion-header[1]</value>
      <webElementGuid>c56ca917-92c6-4c5b-a0e1-a7364d79d0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Transfer'])[4]/preceding::p-accordion-header[1]</value>
      <webElementGuid>3ff278fd-4167-47f1-aef6-20b7033dbf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show Advance Filter']/parent::*</value>
      <webElementGuid>50cfd827-b932-4355-83fe-9c95f105ed47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-accordion-header</value>
      <webElementGuid>52692189-3e05-41da-a92c-adaf6e8ca7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-accordion-header[@id = 'pn_id_201_accordionheader_activePanelValue' and (text() = 'Show Advance Filter' or . = 'Show Advance Filter')]</value>
      <webElementGuid>c6db2d55-7d55-4b89-9b15-55d0ff955f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
