<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>end date</name>
   <tag></tag>
   <elementGuidId>75d46e3a-6d2f-4d65-8368-12ef4b9bd683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pn_id_165_panel']/div/div/table/tbody/tr[5]/td[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c2490469397-23.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc9bdb8a-f332-4105-871a-52a2b14bd357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>77bc0856-1e5d-4e2d-b2ea-e8c424167c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c2490469397-23 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>e8471134-df7f-4ad5-9092-685edef3f9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-11-31</value>
      <webElementGuid>c0cedf1d-f9cc-4f93-992e-783f867792df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>bf3b96ab-54b5-4936-a199-59e6d0ad63f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_165_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2490469397-23 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2490469397-23 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c2490469397-23 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c2490469397-23&quot;]/tr[@class=&quot;ng-tns-c2490469397-23 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c2490469397-23 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c2490469397-23 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>14d709a6-75fa-4993-83c0-8ee432485293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_165_panel']/div/div/table/tbody/tr[5]/td[4]/span</value>
      <webElementGuid>65be4829-e0f0-47bf-943d-33266f07db87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[32]</value>
      <webElementGuid>507dce7b-2054-406f-81a4-6b9d8aacea01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[33]</value>
      <webElementGuid>4313ff7b-fcf7-4c3f-a5dc-7c818618bce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[5]</value>
      <webElementGuid>ff77fa69-a5f7-4283-9ec8-4e1850c10357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>d5b80f3e-77ba-485f-a555-03ab7a880f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/span</value>
      <webElementGuid>f81d2a3e-a7ba-4796-ab7a-98ed24ce791e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '31' or . = '31')]</value>
      <webElementGuid>8d05bd36-bb1b-4fed-92fb-d92eb64992f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
