<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddStep_Compensation Code</name>
   <tag></tag>
   <elementGuidId>366e1591-37ef-4579-a288-9983cc77ffbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card.p-fluid.ng-star-inserted > #saveForm > div > div.grid.align-items-center.px-0 > div.col-3 > p-inputgroup.p-inputgroup > #name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p-inputgroup >> internal:has-text=&quot;40&quot;i >> #name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e634ed8c-ffdf-479e-a24f-26fcbb3feb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>1e0357e9-38f2-4d28-8b0f-6ee2eace45fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f032723d-b3e8-4170-aa4e-c17e91f68130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>compensationCode</value>
      <webElementGuid>b03eb2bb-ada7-4f42-a31e-cbf9ddade047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>compensationCode</value>
      <webElementGuid>c16d305c-5b15-4f19-a20c-c4b05b07e36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 rg-icon ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>acafbac1-54a6-40f6-9ee8-3222ae8f23c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_143_content&quot;)/div[@class=&quot;p-panel-content ng-tns-c3953506556-25&quot;]/app-step-data[@class=&quot;ng-tns-c3953506556-25&quot;]/p-dialog[@class=&quot;ng-tns-c2196985156-29 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-29 p-dialog-mask ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c2196985156-29 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-29 p-dialog-content ng-star-inserted&quot;]/app-step-detail[@class=&quot;ng-tns-c2196985156-29 ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card p-fluid ng-star-inserted&quot;]/form[@id=&quot;saveForm&quot;]/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-3&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>4bb8d273-0621-4c56-8fc8-2c2ad52bcad6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[6]</value>
      <webElementGuid>d8db2a81-8a42-4633-9a5c-24fdec2f8d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[4]/div/p-inputgroup/input</value>
      <webElementGuid>ff331a22-a5c4-4475-9969-eeec2b40e5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/p-inputgroup/input</value>
      <webElementGuid>b6906ce4-1093-45d5-800b-6a70c98d3a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name']</value>
      <webElementGuid>9b583e0a-a74d-454d-b9e0-1f137ab690f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
