<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddStep_Step Name</name>
   <tag></tag>
   <elementGuidId>21ea3684-0fe1-4416-8509-09766f7baa3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-9 > p-inputgroup.p-inputgroup > #name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Step Data&quot;i >> #name >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>631efbd6-e576-4025-aa8f-9fa73f00d99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>67c5f176-dc7f-401a-8f7b-716827a6e40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9d2bee2c-52d0-4d71-8212-87b274652e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>stepName</value>
      <webElementGuid>80b278fd-cfcb-4de3-9d2d-b966a245f3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>stepName</value>
      <webElementGuid>17d78289-f689-4fc9-a8bc-f6a27a4119c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 rg-icon ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>86287fed-c137-435d-beb6-ec8b2334a63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_143_content&quot;)/div[@class=&quot;p-panel-content ng-tns-c3953506556-25&quot;]/app-step-data[@class=&quot;ng-tns-c3953506556-25&quot;]/p-dialog[@class=&quot;ng-tns-c2196985156-29 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-29 p-dialog-mask ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c2196985156-29 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-29 p-dialog-content ng-star-inserted&quot;]/app-step-detail[@class=&quot;ng-tns-c2196985156-29 ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card p-fluid ng-star-inserted&quot;]/form[@id=&quot;saveForm&quot;]/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-9&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>56455310-8004-4e3b-94b8-c5e48d79c489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[4]</value>
      <webElementGuid>bf71c791-6d53-489a-b0a7-cd3da7100ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='saveForm']/div/div/div/p-inputgroup/input)[4]</value>
      <webElementGuid>ee0a9907-6855-4ab8-bb45-0ae490024225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-step-detail/div/div/div/form/div/div/div/p-inputgroup/input</value>
      <webElementGuid>6747cf20-62b3-465d-bfbb-10430d0e9575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name']</value>
      <webElementGuid>7b547e6b-6fbe-479f-aa1b-a0b5e6ff74d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
