<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddStep_Step Service</name>
   <tag></tag>
   <elementGuidId>7092dbae-ca2a-4b81-b40f-56846294402d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Step Data&quot;i >> #name >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>290c1b45-4c61-456e-9a7b-1f236ef78b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>bfc4908c-d4c2-4fc8-92d6-31d1f03463a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>387b6ff3-40db-453c-83cd-b2b94ff215a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>stepService</value>
      <webElementGuid>b320aacd-69ad-4dca-8e42-4804181926b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>stepService</value>
      <webElementGuid>70adf9e2-8b91-47fb-b29d-f234446a7085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 rg-icon ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>566f01da-7024-4f3f-9388-8c18d4662f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_143_content&quot;)/div[@class=&quot;p-panel-content ng-tns-c3953506556-25&quot;]/app-step-data[@class=&quot;ng-tns-c3953506556-25&quot;]/p-dialog[@class=&quot;ng-tns-c2196985156-29 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-29 p-dialog-mask ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c2196985156-29 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-29 p-dialog-content ng-star-inserted&quot;]/app-step-detail[@class=&quot;ng-tns-c2196985156-29 ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card p-fluid ng-star-inserted&quot;]/form[@id=&quot;saveForm&quot;]/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-9&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>e5a985c1-eb83-47d8-b1d9-6a707b948fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[5]</value>
      <webElementGuid>8a920598-45fc-4e37-b1b0-0fc5ee5a3dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='saveForm']/div/div[2]/div/p-inputgroup/input)[2]</value>
      <webElementGuid>d6243853-bf57-4df5-8232-0ab63aac31c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-step-detail/div/div/div/form/div/div[2]/div/p-inputgroup/input</value>
      <webElementGuid>1336badc-9f89-4068-8808-14b963f0df54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name']</value>
      <webElementGuid>113da983-3953-4bbc-a41b-dcaf78bf3da6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
