<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BIFAST-API - GLOBAL</name>
   <tag></tag>
   <elementGuidId>c54cfe40-5c56-45c7-b280-30bf1c7ccf3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/ul/p-selectitem[1]/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pn_id_169_0' and (text() = 'BIFAST-API - GLOBAL' or . = 'BIFAST-API - GLOBAL')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pn_id_169_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BIFAST-API - GLOBAL&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6988d299-300e-44a8-b743-4f47aefc8cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d7d06568-d2f2-4e9a-9677-5bd816977f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-select-option p-focus</value>
      <webElementGuid>ba9bffb5-b6c8-42fd-a1c6-5ab52a133d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_169_0</value>
      <webElementGuid>2088b79f-eb50-481b-a151-0b4a5248c9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BIFAST-API - GLOBAL</value>
      <webElementGuid>d9fd2112-fd41-4d3c-a227-4a7dbd2474cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>42bf1243-704c-4285-a073-6ab975905434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>61817b78-0943-4954-8633-c17834144519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c1e0a02-ed8e-4e0e-9024-d0c30e7ba8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>370655a1-85ee-43a1-ad03-88667ef39a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-highlight</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b168a799-a28b-4d51-b9ca-049aec5b02b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9332c745-cde6-4e75-8a2d-0cefe8febd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BIFAST-API - GLOBAL</value>
      <webElementGuid>80081263-e37c-4ad9-aa51-7897a0fb2290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_169_0&quot;)</value>
      <webElementGuid>61ce66e6-3457-4e55-a337-19595909e8ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pn_id_169_0']</value>
      <webElementGuid>a35f1ffb-93e4-4a0d-bf3b-836918f5b23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pn_id_169_list']/p-selectitem/li</value>
      <webElementGuid>82cf8e81-604d-4e2e-a218-cc412c86556e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>d1379d49-2aa6-4a27-ba34-125c826bc3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BIFAST-CHUB - GLOBAL'])[1]/preceding::li[1]</value>
      <webElementGuid>e966a846-2a64-4445-9c8d-7c4cc23055b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-selectitem/li</value>
      <webElementGuid>d4b45cc0-4510-4460-b91d-6e1d2c81b295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pn_id_169_0' and (text() = 'BIFAST-API - GLOBAL' or . = 'BIFAST-API - GLOBAL')]</value>
      <webElementGuid>ccc4b8ae-f13f-4420-a65f-0b18a5648d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
