<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Testing23  JSON  BMRIIDJA</name>
   <tag></tag>
   <elementGuidId>55c25158-f46f-4681-ba98-95ef73cafb42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-sidebarlayoutrefactor/div/div[2]/app-composite-config-export/div/p-panel/div/div[2]/div/p-card/div/div/div/p-picklist/div/div[2]/p-listbox/div/div[3]/ul/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pn_id_147_source_list_0' and (text() = ' Testing23  JSON | BMRIIDJA ' or . = ' Testing23  JSON | BMRIIDJA ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pn_id_147_source_list_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Testing23 JSON | BMRIIDJA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>456c7d2c-47ce-40f1-8bc8-56952bcecb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0fc09463-9f42-47b4-b589-796ccecb3cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple cdk-drag p-listbox-option ng-star-inserted p-focus</value>
      <webElementGuid>67342698-8dea-4a10-9c21-edb7806d0b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_147_source_list_0</value>
      <webElementGuid>3185b7ab-b456-4a94-b9c7-b672dde69a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>adba2b69-e5d7-436a-bdb4-605c063ec6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d93088b-052d-4413-a8a9-e04b1f6d9761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7a87b23f-6353-4238-aca0-409163c3428e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ariaposinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aeb77b7f-651b-4814-8679-b5b5668a268e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Testing23  JSON | BMRIIDJA </value>
      <webElementGuid>c7b72d23-1f30-4f07-b539-5279fee1af5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_147_source_list_0&quot;)</value>
      <webElementGuid>505ede5c-ab50-4d9f-ba49-b36f5207ee74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pn_id_147_source_list_0']</value>
      <webElementGuid>6552a059-7a02-497c-a408-0b51cc30825b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cdk-drop-list-3']/li</value>
      <webElementGuid>659c9404-3e4e-49cd-87e5-41467ce1da58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search results are available'])[1]/following::li[1]</value>
      <webElementGuid>ae9c048b-b371-4c6d-a0e3-236b3746dffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Composite'])[1]/following::li[1]</value>
      <webElementGuid>d2c08933-a74d-433d-965a-b6b10a75d821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>c587c2aa-42c0-4480-9160-12351b4c9f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pn_id_147_source_list_0' and (text() = ' Testing23  JSON | BMRIIDJA ' or . = ' Testing23  JSON | BMRIIDJA ')]</value>
      <webElementGuid>a1417139-1390-4040-b298-9da237530c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
