<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Reports</name>
   <tag></tag>
   <elementGuidId>dd48aba8-fb53-40f4-a9d9-8a55ffdc0bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p-card:nth-of-type(2) > div.p-card.p-component > div.p-card-body > div.p-card-content > div.flex > div:nth-of-type(2) > p.quick-access-module</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Transfer'])[3]/following::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>05faf807-b708-4067-9028-b933b3e7b65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quick-access-module</value>
      <webElementGuid>8ede9c02-3167-40ce-a879-ef97a019f445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>6d4ac2ca-1593-4e69-a250-a41c09aaabdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-sidebarlayoutrefactor[1]/div[@class=&quot;container max-w-full&quot;]/div[@class=&quot;content transition-all duration-300&quot;]/app-home[1]/div[@class=&quot;home-content py-8&quot;]/div[@class=&quot;quick-access-container&quot;]/p-card[2]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/div[@class=&quot;flex&quot;]/div[2]/p[@class=&quot;quick-access-module&quot;]</value>
      <webElementGuid>f6ac1622-7fae-437f-ad1f-66e417b74818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Transfer'])[3]/following::p[1]</value>
      <webElementGuid>7743d441-fa27-4bec-bf13-47a427b2761a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Transfer'])[2]/following::p[2]</value>
      <webElementGuid>b6063e21-14b9-4f7f-aa08-31350d4ee8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BI-PRM'])[1]/preceding::p[1]</value>
      <webElementGuid>7865d151-384a-4b09-aa27-48527afd34cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Performance'])[2]/preceding::p[2]</value>
      <webElementGuid>8e950a7d-01af-4714-87d9-432c67201cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-card[2]/div/div/div/div/div[2]/p</value>
      <webElementGuid>f15eeec0-3617-4bb7-840f-414da1d97d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>2aba3d9b-b2ff-4844-b7aa-ccae539d09c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
