<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Branch Name</name>
   <tag></tag>
   <elementGuidId>0e71e04b-7b9c-4404-bc9b-24bdc5565924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p-inputgroup >> internal:has-text=&quot;100&quot;i >> #name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>182f0867-7b15-4874-bfad-cb1dc0c37f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>75aa0059-5b07-4ed9-bc14-95f6560630e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a8b9425d-0634-4936-b5ea-d9ec437244ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filterallowed</name>
      <type>Main</type>
      <value>alphaSpace</value>
      <webElementGuid>c253d23a-53c9-4940-8fd2-93134009fe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>branchName</value>
      <webElementGuid>dc0cf76d-8d1e-4772-8517-a47f60d6dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>branchName</value>
      <webElementGuid>aff88eef-bb4b-4bb5-9a79-13e3f3e21f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 rg-icon ng-touched ng-dirty ng-invalid</value>
      <webElementGuid>e302e905-c485-4bc6-83cc-b279c2d25c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-3&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>fef47335-dbcd-4dd8-82d7-f77b13dd753b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[2]</value>
      <webElementGuid>09bffe8a-74b5-446d-a7b3-b3524c7d5a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div[3]/p-inputgroup/input</value>
      <webElementGuid>6c1f048a-0928-4225-97f3-388d59aeb4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p-inputgroup/input</value>
      <webElementGuid>69dd1115-8898-4db6-a17b-559c2f108500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name']</value>
      <webElementGuid>90adf58c-c97b-4cd2-992d-6a7623a3803f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
