<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Activity</name>
   <tag></tag>
   <elementGuidId>e62742c7-74ab-4635-820d-b3a338210b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-autocomplete.p-component.p-inputwrapper.p-focus.p-inputwrapper-focus > input[name=&quot;undefined&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='undefined'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^ActivityUsername$/ >> internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>947340d6-54fd-482b-a46b-ab08544d0c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>61bfdb48-a4bc-479b-803a-913274c1fe34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2cccab4a-c87e-48c1-ab37-cee212db6425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input ng-star-inserted</value>
      <webElementGuid>5f7b757d-ba44-48cb-9e65-20f2c94a732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4d41d30-0d23-49f6-9ebf-48d80dfd1971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a77330bc-4fee-465d-b6fe-1b73debdf1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>3a58c400-190c-47be-94c8-f70bd2fa9e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ddc41fcb-eba6-4bf7-82e6-ceb456d35261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37b2fc2c-78a4-4d1d-ac5b-3887debbd8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[@class=&quot;p-formgrid grid&quot;]/div[@class=&quot;field col-3&quot;]/p-autocomplete[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-autocomplete p-component p-inputwrapper p-focus p-inputwrapper-focus&quot;]/input[@class=&quot;p-inputtext p-component p-autocomplete-input ng-star-inserted&quot;]</value>
      <webElementGuid>aaa2fce9-a355-438b-9dcd-692fc5a22f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='undefined'])[3]</value>
      <webElementGuid>50132f0b-c50f-41a1-b355-a5c8182b8355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div[3]/div[2]/p-autocomplete/div/input</value>
      <webElementGuid>ceb812a0-6e39-4ea5-938d-c8c2acb665f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p-autocomplete/div/input</value>
      <webElementGuid>b0db9408-5f7e-41e0-84a4-f4053e97d24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'undefined']</value>
      <webElementGuid>b838ebde-4008-4a6b-a1a1-300c4dac97c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
