<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_p-inputtext p-component ng-t_b30a64</name>
   <tag></tag>
   <elementGuidId>8fde6081-c68c-40be-ab4b-1b0fe1362a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2303701948-3.w-full.p-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70afc2f1-8dcc-4f3a-9e58-9a970c173050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input</value>
      <webElementGuid>fbcc0395-a20e-44ef-8e4f-1813aef4bfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8d4e0a23-4816-4db8-9df3-ef06fe6661f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Password</value>
      <webElementGuid>b5070ea1-85e5-4595-b1c8-458c75e99bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>026c3803-1b6b-4dd6-9fc3-f822688bda75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77e615d5-47ef-4fe3-8a73-aa6f5b9de06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secret&quot;)/div[@class=&quot;ng-tns-c2303701948-3 p-password-lg w-full p-password p-component p-inputwrapper p-variant-filled&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2303701948-3 w-full p-password-input&quot;]</value>
      <webElementGuid>f0288f0f-037d-4812-8c71-6e67506890bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>087add20-7096-47e7-9e80-9cca1139f8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-password[@id='secret']/div/input</value>
      <webElementGuid>b0e61dd5-04ff-4b95-a673-53bd0818528d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-password/div/input</value>
      <webElementGuid>133354c2-94f4-4809-8c8b-8bf871194c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Masukan Password']</value>
      <webElementGuid>f5cd1a4f-12f6-4737-b0ab-c648cc40333f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
