<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No sign on</name>
   <tag></tag>
   <elementGuidId>9f9af079-cc93-446f-9970-698e1a59e240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-ripple.p-button.p-component.p-confirmdialog-reject-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>028a84a3-28b9-42a2-993f-fb1f5896eb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-button p-component p-confirmdialog-reject-button</value>
      <webElementGuid>7468cb12-132a-48ea-aad9-cc4c438b2dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33a73261-a100-459f-bf24-5ee29bac0046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d3e0cfe-3acc-4d73-973a-94dabd6af4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>dee23d13-be02-4b2a-a45d-1ee759bfee80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>9f33951c-a441-434d-9040-616da371da79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;ng-tns-c2196985156-3 p-dialog-mask p-overlay-mask p-overlay-mask-enter ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c2196985156-3 p-confirmdialog undefined p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-3 p-dialog-footer ng-star-inserted&quot;]/p-button[@class=&quot;ng-tns-c1317319300-0 ng-star-inserted&quot;]/button[@class=&quot;p-ripple p-button p-component p-confirmdialog-reject-button&quot;]</value>
      <webElementGuid>356a4d97-005d-4f9d-a56f-34832b97ec3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>16efb6b9-c187-48a4-8586-40100c928898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are You Sure to Sign On BMRIIDJA - PT Bank Inti Indonesia Tbk. ?'])[1]/following::button[1]</value>
      <webElementGuid>7d8192ce-539d-40fb-92ab-aaccba52dd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::button[2]</value>
      <webElementGuid>a237f3d9-65ab-4dd6-a3f8-7da86862635d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::button[1]</value>
      <webElementGuid>4d14f830-83b0-49c8-beba-b0bc2db78189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p-button/button</value>
      <webElementGuid>5332df1d-6b5a-437c-8e2f-b27460810275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>619c2e23-6600-4571-8c26-bde2af62ec4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
