<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1 Januari</name>
   <tag></tag>
   <elementGuidId>91a5d50b-5354-4dc6-a4f4-87fa4435d336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pn_id_329_panel']/div/div/table/tbody/tr/td[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c133394098-72.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1&quot;s >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef518cb8-1e7b-4370-ba26-99b506d86de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>618fd406-46b0-4d9d-97a2-5c3a80e6b829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c133394098-72 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>7d88821b-81bb-42f3-a70f-edb4407810e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2026-0-1</value>
      <webElementGuid>6708cac8-10ef-4211-a803-66df0b7bea47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>223aadd2-503c-4562-a2ce-07375237f33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_329_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c133394098-72 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c133394098-72 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c133394098-72 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c133394098-72&quot;]/tr[@class=&quot;ng-tns-c133394098-72 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c133394098-72 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c133394098-72 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>e7a10f84-e4cd-44c0-8407-f493f3f20b18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_329_panel']/div/div/table/tbody/tr/td[5]/span</value>
      <webElementGuid>f684ed3e-1110-4fd1-92ab-0bdb90722e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[5]</value>
      <webElementGuid>572f4991-c4dd-4ccf-b176-22c8f14b5e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[6]</value>
      <webElementGuid>11a4c145-97ec-4ee0-b553-33a299209499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[32]</value>
      <webElementGuid>abaf4b4d-4ae8-420d-a8e5-cf550b8c6ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>3e8c637e-e517-4e3f-b435-fc9f23d32ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>573b29f6-13aa-46ed-b759-05abb6b0eebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>cc29b71a-e390-4adc-a1f4-8952efdb29f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
