<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1 Januari</name>
   <tag></tag>
   <elementGuidId>8db06954-1d21-4326-97fb-9525dd498f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-sidebarlayoutrefactor/div/div[2]/app-account-search/div/p-panel[1]/div/div[2]/div/form/div[1]/div[2]/p-datepicker/span/div/div[1]/div/table/tbody/tr[1]/td[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c133394098-48.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1&quot;s >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7f995b4-6c16-4912-83b8-8b70238cae46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>199f8a42-a6a0-4b29-8d1c-89ded96a29be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c133394098-48 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>68d6e4b6-4156-4a3d-90da-a2581ccf46ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2026-0-1</value>
      <webElementGuid>f2cef44d-6f06-42f3-ae4a-ac5de01da0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ed6720e7-4c1b-492b-8cdf-409f1a44f480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_257_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c133394098-48 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c133394098-48 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c133394098-48 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c133394098-48&quot;]/tr[@class=&quot;ng-tns-c133394098-48 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c133394098-48 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c133394098-48 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>38f0318d-83fd-47d5-b516-aa7d64304d28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_257_panel']/div/div/table/tbody/tr/td[5]/span</value>
      <webElementGuid>20e0384b-83ff-4a87-8f9f-cda82233af9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[5]</value>
      <webElementGuid>9d698247-15d6-4c2f-aeaa-233858a0528e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[6]</value>
      <webElementGuid>416108f8-3561-4ee2-a098-fcfc73ef53cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[32]</value>
      <webElementGuid>c0059ab5-0f03-4fea-8022-c5afbced5305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>5fe93883-b479-41e4-a8f8-1fe72f6788fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>cc337f8d-218b-4d16-8a85-537901598e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>d682e7ee-296d-421a-abff-0dcd63683d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
