<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file CSV-SEMICOLON</name>
   <tag></tag>
   <elementGuidId>43a8e254-76cc-4a06-b268-1b65cd26503d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_109_1 > span.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pn_id_109_1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37870c23-f553-4486-a5b3-d9818ef37820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>13c4cd3b-b9be-491f-827d-b77ce68dcbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV-SEMICOLON</value>
      <webElementGuid>69cbc1be-d49a-4dcb-b27d-ada8398e9b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_109_1&quot;)/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>ea8c7e40-d7f9-484c-ad76-9c8d0db1ab8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pn_id_109_1']/span</value>
      <webElementGuid>85c057ae-1e77-437b-b572-bff1828fed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[9]/following::span[1]</value>
      <webElementGuid>99d49791-a417-4d05-8825-7b3c12c9145d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[2]</value>
      <webElementGuid>9eababcf-cbde-4a28-8b8d-0cacda0142e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No selected item'])[1]/preceding::span[1]</value>
      <webElementGuid>6eb936cc-c7e9-49e1-b9fd-f8ad12eea6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>ca1de654-3df0-45ae-9454-19e1fcf9be57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CSV-SEMICOLON' or . = 'CSV-SEMICOLON')]</value>
      <webElementGuid>e6c4b6e0-ad68-42d1-9fb8-a00aab2e60b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
