<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tgl_31</name>
   <tag></tag>
   <elementGuidId>bf0a7e4c-c0da-4c32-be89-4f0885522802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c2490469397-19.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pn_id_108_panel']/div/div/table/tbody/tr[5]/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54b5265e-fdb7-4d75-a8bb-ed065287c16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55f3f85d-a712-4f17-a660-c0dc11889c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c2490469397-19 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>49b82051-edfb-49b3-8dfd-30b97e1f6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-11-31</value>
      <webElementGuid>94f38ef2-d9c9-4885-a8d3-86d585eae28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>7f89d4e6-8245-4a47-a1ee-4c75e81d6c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_108_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2490469397-19 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2490469397-19 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c2490469397-19 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c2490469397-19&quot;]/tr[@class=&quot;ng-tns-c2490469397-19 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c2490469397-19 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c2490469397-19 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>f5cd71a1-3fe2-4559-875b-57e83dbb6dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_108_panel']/div/div/table/tbody/tr[5]/td[4]/span</value>
      <webElementGuid>a77c7acd-ceb9-4443-b235-244fb8e0afec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[32]</value>
      <webElementGuid>f06e724c-2be9-48b7-97b2-6f16be89ea34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[33]</value>
      <webElementGuid>e8039f48-b113-41cd-b676-4ef64a6418b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[5]</value>
      <webElementGuid>f1aeceac-9184-4f8c-8f1c-21e18528fdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>e9b169fd-6662-49b6-864a-a03dfa8adda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/span</value>
      <webElementGuid>08afd35d-a182-4445-9dde-fa3a584abc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '31' or . = '31')]</value>
      <webElementGuid>127917e2-207a-4e77-b138-96bc1502da41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
