<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tgl_1</name>
   <tag></tag>
   <elementGuidId>5bda70a1-68ea-4fd1-9bc4-73f5cbf9ecd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c2490469397-18.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pn_id_107_panel']/div/div/table/tbody/tr/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>483f7184-22b2-4408-89da-4f168e2433a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c24edc5-d292-42cd-bd2e-3269082e82e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c2490469397-18 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>af78710c-fc57-49b9-9e60-eba08cb5d686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-11-1</value>
      <webElementGuid>d084d94e-27a0-4dc8-b47e-12a91209d5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4a06ef4e-61c4-4973-aa34-0fa71c513929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_107_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2490469397-18 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2490469397-18 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c2490469397-18 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c2490469397-18&quot;]/tr[@class=&quot;ng-tns-c2490469397-18 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c2490469397-18 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c2490469397-18 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>f3cd4024-6ce7-4631-91a5-407504d5c067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_107_panel']/div/div/table/tbody/tr/td[2]/span</value>
      <webElementGuid>35047d61-8ee1-4de8-b85e-7111f4f62013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[2]</value>
      <webElementGuid>066513a0-47b4-4046-aa57-761e4d8e64fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[3]</value>
      <webElementGuid>d326978d-95d2-4a80-b68b-2f613fbf5683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[35]</value>
      <webElementGuid>6d2baa36-2051-4344-ba17-96abe85fc208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>92975949-a6a1-4da4-accd-0132944c635b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>10695ea8-6d54-485d-aa89-829c57927315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>37acc785-18c3-44f2-9abf-a793e4934de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
