<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Status_Active</name>
   <tag></tag>
   <elementGuidId>c1fb68f2-c682-4efa-86c2-00375a6c71c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Active']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Active&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42f98f09-01ab-452e-b23e-c34259841a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5e335526-c1bb-43b4-9f34-a5524fe3aebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>f3abe317-f02d-480e-9743-824b34f45d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>691d7853-3134-435a-b7dd-38f53a49920e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>1b9ef9a9-53f7-46d0-a2f8-b7ed22105a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>bf71a7af-9f90-411b-bed4-588977524109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>636c4f20-b560-45b4-b77e-2e6a1cbae22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Active&quot;)</value>
      <webElementGuid>b410bc5e-6a4b-425f-b875-0fe312bf867f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Active']</value>
      <webElementGuid>5682b5a2-77c2-4a35-a227-d71e20fa06c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveFormResponseCode']/div/div[2]/div[3]/div[2]/p-radio-button/div/input</value>
      <webElementGuid>6e197c7b-bc48-4445-8516-b09507befc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-radio-button/div/input</value>
      <webElementGuid>3785b8f0-ad8a-4010-9be4-530c64f5b6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Active' and @name = 'status']</value>
      <webElementGuid>2340e48c-c934-4e99-9b45-b7482ad2fa7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
