<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Status_Inactive</name>
   <tag></tag>
   <elementGuidId>a39eca92-443f-4dde-87b7-896ad1b019b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inactive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Inactive&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de87b59d-c6f9-4121-8871-c959ecc8194b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c4c5f7df-f230-4284-8676-d8084c96aafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>606a40a8-3b93-42c3-ac59-fce120b543c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>1d2ad404-dbec-4c17-8f24-da27a7fd3ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>abb485d9-6cd2-4c97-a5d2-c71ed591439d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>1356cfc4-241f-4019-950d-f44efdd1e08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c8d835c-67c7-4ce1-b52e-e71ba764360a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inactive&quot;)</value>
      <webElementGuid>bafef6c2-d91a-4d22-8497-665c318a5016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inactive']</value>
      <webElementGuid>ac730be4-f311-4258-969c-92f682ca3d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveFormResponseCode']/div/div[2]/div[3]/div/p-radio-button/div/input</value>
      <webElementGuid>ab4bc9ab-ab7b-465f-a476-89513e664535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-radio-button/div/input</value>
      <webElementGuid>8c2c1631-23c8-4b46-9362-345b7c4d6ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Inactive' and @name = 'status']</value>
      <webElementGuid>3f34bbb9-f6ec-4f0e-b442-47abf598a4d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
