<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_status</name>
   <tag></tag>
   <elementGuidId>6b570ab2-c50f-4d43-8ab8-3d46a349c81c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-autocomplete.p-component.p-inputwrapper.p-inputwrapper-filled > input[name=&quot;undefined&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='undefined'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Response CodeStatus$/ >> internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83a086d1-a10f-48a1-95ba-4ae60691886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>f2622a61-b1ad-46d0-834d-21062f169988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c9afe800-d7f3-45ff-bf51-d5050e75c47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input ng-star-inserted p-filled</value>
      <webElementGuid>4737ebda-6a9e-47b7-aefe-4f2c1b563a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edf7a8e1-f161-4284-b3b4-15202036fce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>27efc11a-a248-40b7-9f08-0a08618d00aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>3fe190eb-2878-4303-a492-253ac328f9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>6cb7a510-4563-49cd-9dfb-96e18a0ef9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>93689542-2cbe-4f64-a52f-40b4576476b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[@class=&quot;p-formgrid grid&quot;]/div[@class=&quot;field col-3&quot;]/app-easy-auto-complete[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/p-autocomplete[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;p-autocomplete p-component p-inputwrapper p-inputwrapper-filled&quot;]/input[@class=&quot;p-inputtext p-component p-autocomplete-input ng-star-inserted p-filled&quot;]</value>
      <webElementGuid>d6725a9f-23af-4f38-be39-87615c629def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='undefined'])[2]</value>
      <webElementGuid>bf153e3a-61e4-4f76-a0f5-e265b797108c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div[2]/div[5]/app-easy-auto-complete/p-autocomplete/div/input</value>
      <webElementGuid>6efc2042-1ac3-44fd-9f72-fd233ab6fbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/app-easy-auto-complete/p-autocomplete/div/input</value>
      <webElementGuid>7837968a-22b7-4e9d-b27c-49f1ec265717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'undefined']</value>
      <webElementGuid>2f89e7b2-008b-4c23-8ae2-abc3d084758a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
