<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Proxy Alias</name>
   <tag></tag>
   <elementGuidId>cafd7379-9edd-45fd-ad51-2dd91a619181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proxyAlias']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#proxyAlias</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59029f84-2114-488b-8972-74e2a5b7b23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proxyAlias</value>
      <webElementGuid>05ea1f62-5537-40e1-812c-08748214245d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>proxyAlias</value>
      <webElementGuid>ac146137-8c1e-4f9a-9c62-6ad61c8fbbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>00efbe6f-9c55-404b-a7e6-69345dfca2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proxyAlias&quot;)</value>
      <webElementGuid>c28ba57a-f709-4a8a-88ee-d8851799b8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proxyAlias']</value>
      <webElementGuid>38e5f324-e1f4-4548-bf44-6b77f2d287cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[5]/input</value>
      <webElementGuid>b12ba7a0-d2a3-4f15-9e5f-90ecd358e594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>68dbba8e-d4e3-41a5-9c35-5ba3ec73421c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'proxyAlias']</value>
      <webElementGuid>1b6010a1-558b-4906-b59d-86146b321fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
