<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inactive_Active incoming</name>
   <tag></tag>
   <elementGuidId>ac642db2-cc9b-4daa-a02f-796e708f0d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Active'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e283f95a-027f-4479-a6ca-fb1844494f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2fac79a6-253f-4996-8c5b-35435bbe45aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>38be7a3b-6fef-41a4-a3fc-8d25f7803aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>51604fe5-b70e-485d-9494-58952cb5da08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>d8808d89-4530-477c-83b5-3d49383de825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusIncoming</value>
      <webElementGuid>233bb097-e17f-424e-86fa-e8df0838a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>412ab055-9754-4f62-aa94-eaec88e983a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;flex flex-row gap-3 col-3&quot;]/div[@class=&quot;flex flex-wrap ng-star-inserted&quot;]/p-radio-button[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-radiobutton p-component&quot;]/input[@id=&quot;Active&quot;]</value>
      <webElementGuid>30b635b2-5457-4368-a1bc-1e8322e7bb60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Active'])[2]</value>
      <webElementGuid>0931d18d-6841-4d32-b6c5-aff8d7148fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[3]/div/div[2]/p-radio-button/div/input</value>
      <webElementGuid>87d77260-ab18-492a-bb8b-abd1b0eaefe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/p-radio-button/div/input</value>
      <webElementGuid>0b34b109-1e6e-45a3-b205-6d88e6aedd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Active' and @name = 'statusIncoming']</value>
      <webElementGuid>b6676da8-7dbd-463e-83e0-da704b67266c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
