<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inactive_Active outgoing</name>
   <tag></tag>
   <elementGuidId>3fc929cd-7d51-4364-9b19-b23c17dc61a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Active']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e815d55-5320-4d1c-9ad7-5e8b893f89f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bc36f1b2-b8e2-44f7-82ed-233eab85b783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>7d0eb098-7504-4c95-98c1-a39d8d7c37a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>00425eff-e281-4f10-ba07-3f5b03f237ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>95fb29df-a743-45bb-a10d-40ca041be980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusOutgoing</value>
      <webElementGuid>47d2c368-bc89-4428-b514-8289135d4595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e9b8f59-e46c-416d-b605-131131b6a1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;flex flex-row gap-3 col-3&quot;]/div[@class=&quot;flex flex-wrap ng-star-inserted&quot;]/p-radio-button[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-radiobutton p-component&quot;]/input[@id=&quot;Active&quot;]</value>
      <webElementGuid>f0f3833d-5d6e-46d8-bcc6-5f017e79cbf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Active']</value>
      <webElementGuid>69c008dd-3798-461f-b6e4-3816d9e18a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[2]/div[3]/div[2]/p-radio-button/div/input</value>
      <webElementGuid>e5f51360-6c0f-43f1-bbae-d35271205163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-radio-button/div/input</value>
      <webElementGuid>c34a497a-d55e-40b3-a177-469738c7a117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Active' and @name = 'statusOutgoing']</value>
      <webElementGuid>06b2a424-f245-4b1a-9dda-ec318061ded6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
