<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input bic bank</name>
   <tag></tag>
   <elementGuidId>9d291d28-44c7-4d32-8b9d-c254dc754fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ac13e02-4585-4043-93f2-834b18c0ce30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>4dfe96d0-965d-4303-963d-bffec6c56f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>27201623-b3ca-4f59-84a2-ff5045eae958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filterallowed</name>
      <type>Main</type>
      <value>alphanum</value>
      <webElementGuid>74f9fa07-1d4f-4001-b5e2-8cd7944825df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bankBIC</value>
      <webElementGuid>dd083216-0567-4d4b-b9b6-352cd14981bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bankBIC</value>
      <webElementGuid>dfea124e-5540-47d5-958f-20b1a8ba8c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 rg-icon ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>131675f9-6aaf-4422-98f7-1e15d35f8ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-3&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>630e69a7-ca83-49af-823b-dd250a37d609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[2]</value>
      <webElementGuid>a5a25b9b-b73e-442e-b492-10cf51431e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div[3]/p-inputgroup/input</value>
      <webElementGuid>c107ee81-b10d-4570-a530-94ab4cba7e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p-inputgroup/input</value>
      <webElementGuid>c5fe54e1-1761-4bd5-97c8-5f410c9ce29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name']</value>
      <webElementGuid>96228ff0-2e8d-4db5-a38a-fca29ecb8fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
