<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button close view</name>
   <tag></tag>
   <elementGuidId>83a6c1e3-a843-4ba6-a90c-a555358bb231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-ripple.p-button.p-component.p-button-icon-only.p-button-secondary.p-button-rounded.p-button-text.p-dialog-close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a86cdf1-124c-4013-af3c-1b6bc64d23e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-dialog-close-button</value>
      <webElementGuid>3f50c98e-6cce-4c74-b0a0-b71aa4e2a690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f49f7bc7-5e0e-4a6d-a26f-15d2f289ed87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6a7b007-df94-4e2d-8c92-9d5b65d6b12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>a412c1e8-a0f8-45f1-ae29-b2d74750d447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f79f98f-8495-41e8-9740-4b7a6f038493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden p-unselectable-text&quot;]/app-root[1]/app-sidebarlayoutrefactor[1]/div[@class=&quot;container max-w-full&quot;]/div[@class=&quot;content transition-all duration-300&quot;]/app-template-notif[@class=&quot;ng-star-inserted&quot;]/p-dialog[@class=&quot;p-fluid ng-tns-c2196985156-18 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-18 p-dialog-mask p-overlay-mask p-overlay-mask-enter ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c2196985156-18 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-18 p-dialog-header ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-18 p-dialog-header-actions&quot;]/p-button[@class=&quot;ng-tns-c2196985156-18 ng-star-inserted&quot;]/button[@class=&quot;p-ripple p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-dialog-close-button&quot;]</value>
      <webElementGuid>370940d8-6fa3-44b7-84b9-e516f69f8ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>70a7bbeb-7b2e-4b6f-a1b4-742038247c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Data'])[1]/following::button[2]</value>
      <webElementGuid>9e8af230-c2fa-48c0-ab66-6726770bcf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::button[1]</value>
      <webElementGuid>a98d1727-7019-4f6c-987a-8e61df4e48db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': EMAIL_USER_ACTIVATION'])[1]/preceding::button[1]</value>
      <webElementGuid>7b74c232-301c-4591-abad-5591437d1bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-button[2]/button</value>
      <webElementGuid>a22113bf-65a2-4369-930b-d632e6b67256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>ee6b1de8-eb54-4949-8e23-c57bde6f030d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
