<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_header</name>
   <tag></tag>
   <elementGuidId>851fce8e-3b10-45b6-a314-d19095609eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5a9dfcd-fe39-4b60-a56e-f6f8e69951ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>f525c495-a2c7-42d4-92c3-a3a14eef6882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>f0927ba9-e98d-400c-a98d-eb4d03cff1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>96b87a50-4290-4c6c-89eb-2b5b266b8fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>de0ec9ac-0396-4db6-acd6-9c774883d4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)</value>
      <webElementGuid>62397d49-631f-4b25-812e-dc3c78974172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='header']</value>
      <webElementGuid>2ebf81f5-20d5-4728-a343-d36561759840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_133_content']/div/div[2]/div/input</value>
      <webElementGuid>a573c8df-c27f-4df0-bd5b-8e8b0e19eafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>2f75787a-23c5-4cf2-9230-ed6c6640556e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'header']</value>
      <webElementGuid>99381fb9-e9d5-498d-a43f-04b5045b9c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
