<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input add parameter group</name>
   <tag></tag>
   <elementGuidId>5b810489-6373-45f5-a682-30e6bf43736c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paramGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paramGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3de913f2-84aa-48b9-8fb3-610203eab7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paramGroup</value>
      <webElementGuid>6ae28d6b-d706-4d07-b6a8-6ee597eff9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>paramGroup</value>
      <webElementGuid>68149e72-0975-40ee-b8c2-d0fef2838d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>paramGroup</value>
      <webElementGuid>54aad064-4762-4587-a45a-a1335139408c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4a42bc3e-7ba1-4bc8-8aca-beb71e0eb7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>b281284c-3651-4003-b6b1-ac8f27faa43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paramGroup&quot;)</value>
      <webElementGuid>157fea04-e543-4ac1-818c-2787692c241d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paramGroup']</value>
      <webElementGuid>073db7ab-274a-4bee-ae0c-53f1a0a6ef34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div/div/p-inputgroup/input</value>
      <webElementGuid>fa00ff1d-2f60-45d7-b846-c7026b70c6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>964b6fa4-4118-4d8c-adb1-b79ff23e0030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paramGroup']</value>
      <webElementGuid>f1e88ac4-9850-4d92-b935-eda7929a2902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
