<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button close view detail city</name>
   <tag></tag>
   <elementGuidId>97c30d87-4474-4fef-b347-67b2c2e737be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-ripple.p-button.p-component.p-button-icon-only.p-button-secondary.p-button-rounded.p-button-text.p-dialog-close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[47]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41d1e652-eb42-4cdb-a622-a4426bc02ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-dialog-close-button</value>
      <webElementGuid>7caa1ea4-21c0-4a10-b274-a62b0378bd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab756a56-da03-47ed-9c00-b382be675632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8776098-3dd2-4ab1-8814-a0b13558ab60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>21cb7522-3ab0-4055-b4ee-3c7075b033b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c3a9d390-dd2a-4031-9740-35a35f358e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-unselectable-text&quot;]/app-root[1]/app-sidebarlayoutrefactor[1]/div[@class=&quot;container max-w-full&quot;]/div[@class=&quot;content transition-all duration-300&quot;]/app-city[@class=&quot;ng-star-inserted&quot;]/p-dialog[@class=&quot;ng-tns-c2196985156-18 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-18 p-dialog-mask ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c2196985156-18 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-18 p-dialog-header ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2196985156-18 p-dialog-header-actions&quot;]/p-button[@class=&quot;ng-tns-c2196985156-18 ng-star-inserted&quot;]/button[@class=&quot;p-ripple p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-dialog-close-button&quot;]</value>
      <webElementGuid>1e169a43-da8a-4e22-8a8c-79344a921134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[47]</value>
      <webElementGuid>ad837d60-2d02-4a60-8a2e-e06352b2f588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Data'])[1]/following::button[2]</value>
      <webElementGuid>2cf8bbd1-b332-4883-8ccd-705c3f90672d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City Code'])[2]/preceding::button[1]</value>
      <webElementGuid>8db569cb-bf5d-4a8c-a695-08deb8964689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-button[2]/button</value>
      <webElementGuid>37633717-4600-4d4d-b94e-c0fc6d7b0fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>ed18f9ad-8e45-4736-9aeb-cdda69ee7715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
