<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input city name</name>
   <tag></tag>
   <elementGuidId>6e8d410b-58c5-47de-8d29-558ace127ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd17aed0-bf3b-45db-af53-ef2c7cde272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>357a8f44-a0ce-45c6-9dbc-ebce1d7eacc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c6f88ff6-90b8-48d2-a693-f12a20e0e339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cityName</value>
      <webElementGuid>9431f27b-6e9c-461d-bbb6-745c69198b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cityName</value>
      <webElementGuid>eddca308-4c27-4fbd-ae6a-58e4ccb4428b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 rg-icon ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>77a7f442-8fec-4ac8-99a6-c47220190af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-3&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>5ca35bb8-5af4-449e-9923-673958729029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[2]</value>
      <webElementGuid>5a225f21-2235-4a27-8569-78b232ab8149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div[3]/p-inputgroup/input</value>
      <webElementGuid>13093d33-9c1b-4c88-9721-a6c4ac701cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p-inputgroup/input</value>
      <webElementGuid>3fc37dd3-f3c1-4982-9a45-ef9fbf933b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name']</value>
      <webElementGuid>d794fd30-a8b1-4b90-bbfc-4cb906ffce2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
