<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1 Januari</name>
   <tag></tag>
   <elementGuidId>21d6764f-7dcf-4f4f-b4a9-5efe58e4c5a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-sidebarlayoutrefactor/div/div[2]/app-aggregate-transaction/div/p-panel[1]/div/div[2]/div/form/div[1]/div[2]/p-datepicker/span/div/div[1]/div/table/tbody/tr[1]/td[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c133394098-54.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1&quot;s >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>864f9535-c853-4981-abeb-c87ec75b4669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d6ad33a-9346-494a-a80f-336eef11fc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c133394098-54 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>17efd2f1-7d4b-4111-b983-1d77a38cf09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2026-0-1</value>
      <webElementGuid>78c9c915-fd4a-4eb4-a764-b32129254259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>049f11ae-fcb3-474a-9f0b-e3d3cbd4935e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_275_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c133394098-54 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c133394098-54 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c133394098-54 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c133394098-54&quot;]/tr[@class=&quot;ng-tns-c133394098-54 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c133394098-54 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c133394098-54 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>e991fd98-3f35-4940-97bd-264db128c48f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_275_panel']/div/div/table/tbody/tr/td[5]/span</value>
      <webElementGuid>15b8611c-c957-496f-b823-9fabe9089e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[5]</value>
      <webElementGuid>9b49f227-b678-49b5-a76c-1c2cf0e17d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[6]</value>
      <webElementGuid>d2afd4d7-1134-4183-a434-de99f7ac5cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[32]</value>
      <webElementGuid>4100570b-b94d-4a41-bd47-91b6ff375064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>4d114751-fdd5-4065-a66c-d8cf7eebeee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>ba250509-0c4b-4690-a7bc-5706659ef7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>cd2ef022-7698-4e24-b615-ec037bcd9d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
