<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1 Desember</name>
   <tag></tag>
   <elementGuidId>935ec164-384a-4c34-9232-ff9be2fbf13f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-sidebarlayoutrefactor/div/div[2]/app-settlement-history/div/p-panel[1]/div/div[2]/div/form/div[1]/div[2]/p-datepicker/span/div/div[1]/div/table/tbody/tr[1]/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.ng-tns-c133394098-148.p-datepicker-day.p-datepicker-day-selected.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td >> internal:has-text=&quot;1 1&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35f77cac-edc0-4f21-9b7e-721c4bce2a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02be1a5e-4d18-42f3-b325-d1cdda89f6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c133394098-148 p-datepicker-day p-datepicker-day-selected ng-star-inserted</value>
      <webElementGuid>97487ec6-141a-4dbb-974f-5569ab59a30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-11-1</value>
      <webElementGuid>6d7400a6-df89-474d-b2e0-7574baeaee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3396c2b0-bc40-43e9-9e9e-1435def03078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>75d9437e-8612-472f-9d3e-693955160243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_386_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c133394098-148 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c133394098-148 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c133394098-148 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c133394098-148&quot;]/tr[@class=&quot;ng-tns-c133394098-148 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c133394098-148 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c133394098-148 p-datepicker-day p-datepicker-day-selected ng-star-inserted&quot;]</value>
      <webElementGuid>fa0a779c-f7f6-481a-8f74-6c8b585b5036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_386_panel']/div/div/table/tbody/tr/td[2]/span</value>
      <webElementGuid>d25fe668-880d-4543-96c3-fa27a9da4b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[2]</value>
      <webElementGuid>cd3375ef-14d1-4403-a17f-225ba02d3e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[3]</value>
      <webElementGuid>4a8c0bf9-6bc6-4b9d-b85b-49cb6e4533f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[35]</value>
      <webElementGuid>6d8d39ea-d260-4e40-ab8e-e827eae74673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>54476ae3-c9a7-4cec-8c01-49b11387326c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>1666c529-0226-4d31-add5-93dcd68a29dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>fd598139-5be9-4c7e-b80a-6e69ba9f1e88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
