<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KOMI Ref</name>
   <tag></tag>
   <elementGuidId>fbc605a4-8b8f-46c1-80cc-8ad6ca1502d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#komiUniqueId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='komiUniqueId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dd6a8f5-03cb-42aa-914a-021e601fdfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>komiUniqueId</value>
      <webElementGuid>6c6e8861-b2f7-49e7-8722-92cf9e9025c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>komiUniqueId</value>
      <webElementGuid>0d2225ec-913b-46f9-9a2b-a0224bb7a1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0b77587f-59a1-4ff5-8358-0c1a8fa65272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;komiUniqueId&quot;)</value>
      <webElementGuid>4dcfa859-a687-4551-8a40-9ec89b0d099f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='komiUniqueId']</value>
      <webElementGuid>361443c6-9fd8-4c88-8e2a-a2344b4e9a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[17]/input</value>
      <webElementGuid>462a4c67-e703-4d2c-9f3e-7998153f9731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/input</value>
      <webElementGuid>8f22023a-011c-42e9-82a1-b3ebad9af73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'komiUniqueId']</value>
      <webElementGuid>a01bb31c-5ac5-4125-a724-84e43233aa25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
