<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number</name>
   <tag></tag>
   <elementGuidId>9574392f-c340-4411-9027-a32e8c779fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27838c9e-7677-4495-90e1-41d7167c1b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>76968e10-f9b0-4af3-9a3e-bc0c7b604011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>ef6d1beb-8482-4aec-867c-93314eecaae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5c66f286-e280-42a1-95ff-5f9a0b893075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountNo&quot;)</value>
      <webElementGuid>09aafd5b-a3c6-48da-a03c-dd97fea3540f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountNo']</value>
      <webElementGuid>1c832481-cecf-4a7f-871e-afa37cd7943c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[11]/input</value>
      <webElementGuid>0c19fb71-830f-4c82-8765-ca37e398161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>ad3486c2-38b6-4efd-9a5b-5fc19d9d284b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accountNo']</value>
      <webElementGuid>5ab13b47-5fa4-4d34-a748-10908d5fb2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
