<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Parameter Group</name>
   <tag></tag>
   <elementGuidId>adb28ed3-bd5a-4d80-bb9d-9c86c8f1d857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paramGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paramGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#paramGroup</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb5d5614-cc29-47e5-89d2-d23aae3b8ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paramGroup</value>
      <webElementGuid>c4e18ce0-d4ae-47b9-8dbc-e5d7600d04c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>paramGroup</value>
      <webElementGuid>14818aed-8b34-427b-bf71-c28810a59546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>paramGroup</value>
      <webElementGuid>7109bec4-6991-4267-9dff-03dab72f31ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e018a5d0-5a11-4192-ab81-c37da4ed1804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>0347278f-cce1-47af-8986-deb4be0bbdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paramGroup&quot;)</value>
      <webElementGuid>89ccc1aa-4443-4bd1-a950-a39d31e2c7be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paramGroup']</value>
      <webElementGuid>dd5055fe-f270-44f5-9258-8c5302af06ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div/div/p-inputgroup/input</value>
      <webElementGuid>9f88e772-e0cb-419b-8b00-28b46dcf4f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ff8153d3-48ae-493d-be96-788499f201d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paramGroup']</value>
      <webElementGuid>91410af5-154e-4635-9fad-08a30a21577c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
