<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Parameter Description</name>
   <tag></tag>
   <elementGuidId>9b2df106-b2c7-4a17-b0eb-f3db2cab10e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.p-inputtext.p-component.p-1.w-12.h-32.textarea-desc.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[type=&quot;text&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8867350d-783e-4bd1-9d4d-272d41e2777d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>004c1c7b-c1da-4a01-87ea-aff4622accca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>paramDesc</value>
      <webElementGuid>471d6654-e576-4241-a6a6-b88f350cd714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-1 w-12 h-32 textarea-desc ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>349f8d0a-8df3-45c8-adb6-ae642b6eabd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>aac7b792-b27b-46af-9bfa-3ffe7f1830a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[1]/div[1]/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;col-3&quot;]/p-inputgroup[@class=&quot;p-inputgroup&quot;]/textarea[@class=&quot;p-inputtext p-component p-1 w-12 h-32 textarea-desc ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>7532bd00-e8e4-4e05-9443-f8229cade4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>b922f3fb-2eaf-4b33-b350-0218a10f7d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div/div/div[3]/p-inputgroup/textarea</value>
      <webElementGuid>5ecede99-6c4f-4e4a-b140-0376b61f9a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>02297b4c-bc3e-470f-92ab-8e45e31f1e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text']</value>
      <webElementGuid>35ba33e7-eee5-48a0-b272-4f7a1bba8dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
