<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input current password</name>
   <tag></tag>
   <elementGuidId>c8e125c1-3612-4fba-8d74-ec2026e70e6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2303701948-19.p-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e40a469-5eff-4ebb-aa65-54c31e59c674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2303701948-19 p-password-input</value>
      <webElementGuid>fb9df895-857a-4e8d-95f8-9be2dd0e4a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e40c75f-31a4-430a-96b6-a11307df99be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4518dbc4-af8f-4af7-bc1b-5d625365bf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldSecret&quot;)/div[@class=&quot;ng-tns-c2303701948-19 p-password p-component p-inputwrapper p-variant-filled p-inputwrapper-focus&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2303701948-19 p-password-input&quot;]</value>
      <webElementGuid>13f60868-ac5c-444e-86a9-9b278797fcfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>0058c167-892d-4336-ab10-d4f817899988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-password[@id='oldSecret']/div/input</value>
      <webElementGuid>9141cc5a-3ce9-4ee8-8feb-5eeefb48bf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>31df90ca-9933-452b-a2f0-175465d318e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>47448f25-923f-4ee8-9a1e-c7762624191b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
