<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input end date</name>
   <tag></tag>
   <elementGuidId>d5424994-4786-4e30-be13-7616adc4d2d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2490469397-33.p-datepicker-input.p-filled.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa9bf13a-daa2-4b3f-bcd4-a23ab88e3e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c790205-ce78-45b8-b7a3-2bdc939a6408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3129acc0-a1e2-432c-94fb-5c61b9e9572d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>838bb79b-aaa0-4304-8e06-6faec205a869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>0f26aa65-1ea8-458e-b177-92cb12074e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12655d8b-b30d-41a0-8ec7-a7eafdb266ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2490469397-33 p-datepicker-input p-filled ng-star-inserted</value>
      <webElementGuid>2679d14c-42c9-407c-9aa4-7fc97320a852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cda660b9-713a-461b-b982-c2d4e7b877c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_200_panel</value>
      <webElementGuid>e1dc1df3-fa52-465b-8220-8b8eccd46057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)/div[@class=&quot;grid align-items-center px-0&quot;]/div[@class=&quot;field col-3&quot;]/p-calendar[@class=&quot;w-12 ng-tns-c2490469397-33 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c2490469397-33 p-datepicker p-component p-inputwrapper p-inputwrapper-filled p-inputwrapper-focus p-focus&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2490469397-33 p-datepicker-input p-filled ng-star-inserted&quot;]</value>
      <webElementGuid>aad9e79e-e15c-4d36-bf1f-79be1be37c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>a8c578cf-bbae-4cd7-b2a7-e90123c2efd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='saveForm']/div/div[5]/p-calendar/span/input</value>
      <webElementGuid>d8791b10-b990-4fe8-8eaf-2b2981aaa2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p-calendar/span/input</value>
      <webElementGuid>0bb897bf-0f90-4597-b861-7181b6b26c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>04fb253f-1dce-4dca-92a3-dc67db4b9788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
